language: java
jdk: oraclejdk8
dist: trusty
sudo: required
services:
  - docker
env:
  - DOCKER_REPO_SLUG=plantlogic/user-service
script:
  - mvn clean package
  - docker build -t $DOCKER_REPO_SLUG:latest .
after_success:
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then
      docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD ;
      docker push $DOCKER_REPO_SLUG ;
    fi
