version: '3.7'
services:
  userservice:
    build: ./
    environment:
      - APP_NAME=PlantLogic
    env_file:
      - ./smtp-config.env
    depends_on:
      - userdb
    networks:
      usernet:
    ports:
      - 127.0.0.1:8080:8080
  userdb:
    image: 'mongo:4'
    restart: always
    networks:
      usernet:
        aliases:
        - userdb
    volumes:
      - ./mongodb:/data/db

networks:
  usernet: