version: '3.7'
services:
  app:
    build: ./
    restart: always
    depends_on:
      - database
    networks:
      database:
    ports:
      - 127.0.0.1:8080:8080
  database:
    image: 'mongo:4'
    restart: always
    networks:
      database:
        aliases:
        - database
    volumes:
      - ./mongodb:/data/db

networks:
  database: